# Generated by Django 6.0.4 on 2026-05-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва гри')),
                ('developer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Розробник')),
                ('release_year', models.IntegerField(verbose_name='Рік випуску')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва платформи')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Виробник (Nintendo, Sega, Sony тощо)')),
                ('release_year', models.IntegerField(verbose_name='Рік випуску')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('MINT', 'Ідеальний (Mint)'), ('CIB', 'У коробці з інструкцією (CIB)'), ('GOOD', 'Хороший (Loose/Good)'), ('POOR', 'Поганий (Poor/Damaged)')], max_length=20, verbose_name='Стан')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна покупки')),
                ('acquired_date', models.DateField(blank=True, null=True, verbose_name='Дата придбання')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Нотатки (дефекти, особливості)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection', to=settings.AUTH_USER_MODEL, verbose_name='Колекціонер')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='inventory.game', verbose_name='Гра')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='inventory.platform', verbose_name='Платформа'),
        ),
    ]
