# Generated by Django 6.0.4 on 2026-05-02 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='items_photos/', verbose_name='Фото екземпляра'),
        ),
    ]
