# Generated by Django 6.0.4 on 2026-05-04 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='platform',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_year',
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='completeness',
            field=models.CharField(choices=[('loose', 'Тільки картридж/диск (Loose)'), ('cib', 'Повний комплект (CIB)'), ('boxed', 'Картридж + Коробка'), ('manual', 'Картридж + Мануал'), ('sealed', 'Запакована (Sealed)')], default='loose', max_length=20, verbose_name='Комплектація'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='is_reproduction',
            field=models.BooleanField(default=False, verbose_name='Це репродукція (не оригінал)'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='region',
            field=models.CharField(choices=[('ntsc_u', 'NTSC-U (Північна Америка)'), ('ntsc_j', 'NTSC-J (Японія)'), ('pal', 'PAL (Європа / Австралія)'), ('unknown', 'Невідомо / Інше')], default='unknown', max_length=20, verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='condition',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Стан (опис)'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.game'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Нотатки'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='items_photos/', verbose_name='Головне фото'),
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Назва гри'),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва локації (напр., Моя квартира)')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name="Адреса (необов'язково)")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Кімната (напр., Вітальня)')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory.location')),
            ],
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Місце (напр., Стелаж 1, Коробка А)')),
                ('is_box', models.BooleanField(default=False, verbose_name='Це закрита коробка?')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='inventory.room')),
            ],
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.storageunit', verbose_name='Місцезнаходження'),
        ),
        migrations.DeleteModel(
            name='ItemImage',
        ),
        migrations.DeleteModel(
            name='Platform',
        ),
    ]
