# Generated by Django 6.0.4 on 2026-05-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='edition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Видання (напр. Big Box, Jewel)'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='inventory_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Лот / Інвентарний номер'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='item_name',
            field=models.CharField(default='Нова гра', help_text="Наприклад: 'Doom (Big Box)'", max_length=255, verbose_name='Назва вашої копії'),
        ),
    ]
