# Generated by Django 6.0.4 on 2026-05-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_collectionitem_edition_collectionitem_inventory_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='inventory_code',
        ),
        migrations.AlterField(
            model_name='collectionitem',
            name='edition',
            field=models.CharField(blank=True, choices=[('', 'Не вказано / Стандартне'), ('Big Box', 'Big Box (Велика картонна коробка)'), ('Jewel Case', 'Jewel Case (Стандартна CD коробка)'), ('Keep Case', 'Keep Case (Пластикова DVD/Blu-ray коробка)'), ('SteelBook', 'SteelBook (Металевий кейс)'), ('Limited Edition', 'Лімітоване видання (Limited)'), ('Collector Edition', "Колекційне видання (Collector's)"), ('Greatest Hits', "Greatest Hits / Platinum / Player's Choice"), ('Other', 'Інше')], max_length=50, null=True, verbose_name='Видання'),
        ),
    ]
