# Generated by Django 6.0.4 on 2026-05-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_collectionitem_inventory_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='last_updated_market',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оновлення ціни'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='market_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ринкова ціна ($)'),
        ),
    ]
