# Generated by Django 6.0.4 on 2026-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_collectionitem_last_updated_market_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageunit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Зробити дашборд публічним (доступ за QR-кодом без логіну)'),
        ),
    ]
